In [ ]:
import numpy as np

In [ ]:
X=np.array([[4.7,3.2,1.3],[4.6,3.1,1.5],[5,3.6,1.4]])
X

array([[4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4]])

In [ ]:
X_BARRA=np.array([[X.T[0].sum()/3],[X.T[1].sum()/3],[X.T[2].sum()/3]])

In [ ]:
X_BARRA.T

array([[4.76666667, 3.3       , 1.4       ]])

In [ ]:
X_CENT=X-X_BARRA.T
X_CENT

array([[-6.66666667e-02, -1.00000000e-01, -1.00000000e-01],
       [-1.66666667e-01, -2.00000000e-01,  1.00000000e-01],
       [ 2.33333333e-01,  3.00000000e-01,  2.22044605e-16]])

In [ ]:
np.set_printoptions(suppress=True)  # Suprime la notación científica
print(X_CENT)

[[-0.06666667 -0.1        -0.1       ]
 [-0.16666667 -0.2         0.1       ]
 [ 0.23333333  0.3         0.        ]]


In [ ]:
X_CENT.T

array([[-0.06666667, -0.16666667,  0.23333333],
       [-0.1       , -0.2       ,  0.3       ],
       [-0.1       ,  0.1       ,  0.        ]])

In [ ]:
S=np.dot(X_CENT.T,X_CENT)*(1/3)

In [ ]:
S

array([[ 0.02888889,  0.03666667, -0.00333333],
       [ 0.03666667,  0.04666667, -0.00333333],
       [-0.00333333, -0.00333333,  0.00666667]])

In [ ]:
valores_propios, vectores_propios = np.linalg.eig(S)

In [ ]:
valores_propios

array([0.07582333, 0.        , 0.00639889])

In [ ]:
#SA=lambdaA donde A es una matriz 3x1 cuyos elementos son el peso de los componentes
vectores_propios

array([[ 0.61720358,  0.78633365, -0.02718706],
       [ 0.78389991, -0.61159284,  0.10702866],
       [-0.06753282,  0.08737041,  0.99388416]])

In [ ]:
A_1=vectores_propios[:,0]
A_2=vectores_propios[:,1]
A_3=vectores_propios[:,2]
print(f"{A_1},{A_2},{A_3}")

[ 0.61720358  0.78389991 -0.06753282],[ 0.78633365 -0.61159284  0.08737041],[-0.02718706  0.10702866  0.99388416]


In [ ]:
A_1.T

array([ 0.61720358,  0.78389991, -0.06753282])

In [ ]:
#Condición (A_1)^T(A_1)=1
c1=np.dot(A_1.T,A_1)
c2=np.dot(A_2.T,A_2)
c3=np.dot(A_3.T,A_3)
print(f"c1={c1}, c2={c2}, c3={c3}. Se cumple la condición")

c1=0.9999999999999999, c2=0.9999999999999999, c3=0.9999999999999999. Se cumple la condición


In [ ]:
Z_1=np.dot(S,A_1)
Z_2=np.dot(S,A_2)
Z_3=np.dot(S,A_3)
print(f"Z_1={Z_1}, Z_2={Z_2}, Z_3={Z_3}")

Z_1=[ 0.04679843  0.0594379  -0.00512056], Z_2=[-0. -0.  0.], Z_3=[-0.00017397  0.00068486  0.00635976]


In [ ]:
Z_A=0.07582333*A_1
Z_B=0*A_2
Z_C=0.00639889*A_3
print(f"Z_A={Z_A}, Z_B={Z_B}, Z_C={Z_C}")


Z_A=[ 0.04679843  0.0594379  -0.00512056], Z_B=[ 0. -0.  0.], Z_C=[-0.00017397  0.00068486  0.00635976]


In [ ]:
Z_4 = np.array([Z_1, Z_2, Z_3])
Z_4
Z_D = np.array([Z_A, Z_B, Z_C])
Z_D
if np.allclose(Z_D, Z_4, atol=1e-8):
    print("Son iguales y cumple la condicion Sa_i=lamdba_ia_i")
else:
    print("No Son iguales y no cumple la condicion Sa_i=lamdba_ia_i")

Son iguales y cumple la condicion Sa_i=lamdba_ia_i


In [ ]:
Z_uno = np.dot(X_CENT,A_1)
Z_dos = np.dot(X_CENT,A_2)
Z_tres = np.dot(X_CENT,A_3)
print(f"Z_uno={Z_uno}, Z_dos={Z_dos}, Z_tres={Z_tres}")

Z_uno=[-0.11278361 -0.26640053  0.37918414], Z_dos=[0. 0. 0.], Z_tres=[-0.10827881  0.08251386  0.02576495]
